### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by llbranco** [pihomeserver/Pi-Hotspot-Script#11]
package nginx missing

all downloads should happen before instalation progress
this way we can download all required softwares by pi-hotspot-script using 3g/4g/bluetooth/wlan internet, instead of ONLY eth0

this script should have some "if/then" to check previously changes
doing this if your install crash u can continue without additional issues, like "mysql table alrealy exist"

thank you for this amazing script
cheers

**Comment by pihomeserver** [comment]
Hi
First thanks to help improving the script

About Nginx, the install is made at line 250 so it should not be missing

I agree about the recovery. That's why there is a jumpto instruction in comments but i did not implemented it yet. Your are welcome to add it :-)

And i will put all apt-get at the beginning of the script after the update

Nice to hear that it helped (and worked)
